services:
  backend:
    build: backend
    environment:
      - SPANNER_EMULATOR_HOST=db:9010
      - MYAPP_GCLOUD_PROJECT=coolio
      - MYAPP_SPANNER_INSTANCE_ID=test-instance
      - MYAPP_SPANNER_DATABASE_ID=coolio-dev
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    restart: always
    expose:
      - 9010
